name: Beta Deployment

on:
  push:
    tags-ignore:
      - 'v1'
      - 'v1.*'

jobs:
  deploy:
    name: Deploying
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploying
        uses: wei/rclone@v1
        env:
          RCLONE_CONF: ${{ secrets.ANFORCOM_RCLONE_CONF }}
        with:
          args: copy -L --exclude .git/ --exclude vendor/ ./ anforcom:public_html/beta/
