name: Beta Deployment

on: push

jobs:
  deploy:
    name: Deploying
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Composer package cache
        uses: actions/cache@v2
        with:
          path: ./vendor
          key: compsoer-${{ hashFiles('composer.lock') }}
          restore-keys: |
            composer-

      - name: Composer package install
        run: composer install --no-interaction

      - name: Deploying
        uses: wei/rclone@v1
        env:
          RCLONE_CONFIG_ANFORCOM_TYPE: webdav
          RCLONE_CONFIG_ANFORCOM_URL: ${{ secrets.ANFORCOM_WEBDISK_URL }}
          RCLONE_CONFIG_ANFORCOM_VENDOR: other
          RCLONE_CONFIG_ANFORCOM_USER: ${{ secrets.ANFORCOM_WEBDISK_USERNAME }}
          RCLONE_CONFIG_ANFORCOM_PASS: ${{ secrets.ANFORCOM_WEBDISK_PASSWORD }}
        with:
          args: copy ./ anforcom:beta/
