name: Beta Deployment

on: push

jobs:
  deploy:
    name: Deploying
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Installing rclone
        run: curl https://rclone.org/install.sh | sudo bash

      - name: Deploying
        env:
          RCLONE_CONFIG_ANFORCOM_TYPE: webdav
          RCLONE_CONFIG_ANFORCOM_VENDOR: other
          RCLONE_CONFIG_ANFORCOM_URL: ${{ secrets.ANFORCOM_WEBDISK_URL }}
          RCLONE_CONFIG_ANFORCOM_USER: ${{ secrets.ANFORCOM_WEBDISK_USERNAME }}
          RCLONE_CONFIG_ANFORCOM_PASS: ${{ secrets.ANFORCOM_WEBDISK_PASSWORD }}
        run: rclone copy -L --exclude .git/ --exclude vendor/ ./ anforcom:public_html/beta/
