name: Beta Deployment

on: push

jobs:
  deploy:
    name: Deploying
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Installing rclone
        run: curl https://rclone.org/install.sh | sudo bash

      - name: Deploying
        env:
          RCLONE_CONFIG_ANFORCOM_TYPE: ftp
          RCLONE_CONFIG_ANFORCOM_PORT: 21
          RCLONE_CONFIG_ANFORCOM_TLS: false
          RCLONE_CONFIG_ANFORCOM_HOST: ${{ secrets.ANFORCOM_FTP_HOST }}
          RCLONE_CONFIG_ANFORCOM_USER: ${{ secrets.ANFORCOM_FTP_USER }}
          RCLONE_CONFIG_ANFORCOM_PASS: ${{ secrets.ANFORCOM_FTP_PASS }}
        run: rclone copy --check-first -L --exclude .git/ --exclude ./vendor/ --transfers 5 --checkers 5 ./ anforcom:public_html/beta/
