name: Beta Deployment

on:
  push:
    tags-ignore:
      - 'v1'
      - 'v1.*'

jobs:
  deploy:
    name: Deploying
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Installing rclone
        run: sudo apt update && sudo apt install rclone

      - name: Deploying
        env:
          RLCONE_CONFIG_ANFORCOM_TYPE: webdav
          RLCONE_CONFIG_ANFORCOM_VENDOR: other
          RLCONE_CONFIG_ANFORCOM_URL: ${{ secrets.ANFORCOM_WEBDISK_URL }}
          RLCONE_CONFIG_ANFORCOM_USER: ${{ secrets.ANFORCOM_WEBDISK_USERNAME }}
          RLCONE_CONFIG_ANFORCOM_PASS: ${{ secrets.ANFORCOM_WEBDISK_PASSWORD }}
        run: rclone copy -L --exclude .git/ --exclude vendor/ ./ anforcom:public_html/beta/
