name: Production Deployment

on:
  push:
    tags:
      - 'v1'
      - 'v1.*'

jobs:
  deploy:
    name: Deploying
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Installing rclone
        run: curl https://rclone.org/install.sh | sudo bash

      - name: Deploying
        env:
          RCLONE_CONFIG_ANFORCOM_TYPE: ftp
          RCLONE_CONFIG_ANFORCOM_PORT: 21
          RCLONE_CONFIG_ANFORCOM_TLS: false
          RCLONE_CONFIG_ANFORCOM_HOST: ${{ secrets.ANFORCOM_FTP_HOST }}
          RCLONE_CONFIG_ANFORCOM_USER: ${{ secrets.ANFORCOM_FTP_USER }}
          RCLONE_CONFIG_ANFORCOM_PASS: ${{ secrets.ANFORCOM_FTP_PASS }}
        run: 'rclone copy -L --check-first --exclude .git/ --exclude ./vendor/ --transfers 1 --checkers 1 ./ anforcom:'

      - name: Copying public to public_html
        env:
          RCLONE_CONFIG_ANFORCOM_TYPE: ftp
          RCLONE_CONFIG_ANFORCOM_PORT: 21
          RCLONE_CONFIG_ANFORCOM_TLS: false
          RCLONE_CONFIG_ANFORCOM_HOST: ${{ secrets.ANFORCOM_FTP_HOST }}
          RCLONE_CONFIG_ANFORCOM_USER: ${{ secrets.ANFORCOM_FTP_USER }}
          RCLONE_CONFIG_ANFORCOM_PASS: ${{ secrets.ANFORCOM_FTP_PASS }}
        run: rclone copy -L --check-first --transfers 1 --checkers 1 anforcom:public/ anforcom:public_html/
